platform :ios, '6.0'
pod 'Parse', '~> 1.2'
pod 'TestFlightSDK', '~> 2.0'
pod 'ActionSheetPicker', '~> 0.0'
pod 'FormatterKit', '~> 1.2'
pod 'ODRefreshControl', '~> 1.1'
pod 'SVProgressHUD', '~> 0.9'
pod 'RATreeView', '~> 0.0'
